package view;

import dao.ProdutoDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Produto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chris
 */
public class TelaCadProduto extends javax.swing.JFrame {

    String usuarioLogado;
    private boolean modoEdicao = false;
    private int idProdutoEdicao = 0;

    /**
     * Creates new form TelaCadInstrumento
     */
    TelaCadProduto() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setTitle("Cadastro de Produtos - SoundWave");
    }

    TelaCadProduto(String usuarioLogado) {
        this();
        this.usuarioLogado = usuarioLogado;
    }

    public void ativarEdicao(
            int idProduto,
            String modelo,
            String categoria,
            String tipo,
            String marca,
            String valor,
            String estoque
    ) {
        modoEdicao = true;
        idProdutoEdicao = idProduto;
        
        setTitle("Edição de Produtos - SoundWave");
        BtnCad.setText("Atualizar");
        title.setText("Editar Produto");

        TxfModelo.setText(modelo);
        ComboCat.setSelectedItem(categoria);
        ComboTipo.setSelectedItem(tipo);
        ComboMarca.setSelectedItem(marca);
        TxFValor.setText(valor);
        TxFEstoque.setText(estoque);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        TxfModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxFEstoque = new javax.swing.JTextField();
        TxFValor = new javax.swing.JTextField();
        BtnCad = new javax.swing.JButton();
        ComboTipo = new javax.swing.JComboBox<>();
        ComboCat = new javax.swing.JComboBox<>();
        ComboMarca = new javax.swing.JComboBox<>();
        BtnVoltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro/Atualização de produto - SoundWave");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Cadastro de Produtos");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        TxfModelo.setBackground(new java.awt.Color(255, 255, 255));
        TxfModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfModeloActionPerformed(evt);
            }
        });
        jPanel1.add(TxfModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 690, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estoque");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        TxFEstoque.setBackground(new java.awt.Color(255, 255, 255));
        TxFEstoque.setForeground(new java.awt.Color(0, 0, 0));
        TxFEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxFEstoqueKeyTyped(evt);
            }
        });
        jPanel1.add(TxFEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 160, 40));

        TxFValor.setBackground(new java.awt.Color(255, 255, 255));
        TxFValor.setForeground(new java.awt.Color(0, 0, 0));
        TxFValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxFValorKeyTyped(evt);
            }
        });
        jPanel1.add(TxFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 290, 40));

        BtnCad.setBackground(new java.awt.Color(25, 118, 210));
        BtnCad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCad.setForeground(new java.awt.Color(255, 255, 255));
        BtnCad.setText("Salvar");
        BtnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 680, 40));

        ComboTipo.setBackground(new java.awt.Color(255, 255, 255));
        ComboTipo.setForeground(new java.awt.Color(0, 0, 0));
        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", " " }));
        ComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoActionPerformed(evt);
            }
        });
        jPanel1.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 290, 40));

        ComboCat.setBackground(new java.awt.Color(255, 255, 255));
        ComboCat.setForeground(new java.awt.Color(0, 0, 0));
        ComboCat.setMaximumRowCount(6);
        ComboCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Corda", "Sopro", "Percussão", "Teclas", "Acessório", "Outro" }));
        ComboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCatActionPerformed(evt);
            }
        });
        jPanel1.add(ComboCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 300, 40));

        ComboMarca.setBackground(new java.awt.Color(255, 255, 255));
        ComboMarca.setForeground(new java.awt.Color(0, 0, 0));
        ComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", " " }));
        ComboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(ComboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 300, 40));

        BtnVoltar.setBackground(new java.awt.Color(25, 118, 210));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Categoria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxfModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfModeloActionPerformed

    private void ComboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMarcaActionPerformed

    private void BtnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadActionPerformed
        // TODO add your handling code here:
        // validacao campo modelo

        try {
            // validacoes
            if (TxfModelo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o nome!");
                TxfModelo.requestFocus();
                return;
            }

            if (TxFValor.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o valor!");
                TxFValor.requestFocus();
                return;
            }

            if (TxFEstoque.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o estoque!");
                TxFEstoque.requestFocus();
                return;
            }

            if (ComboCat.getSelectedItem().equals("Selecione")) {
                JOptionPane.showMessageDialog(this, "Selecione a categoria!");
                return;
            }

            if (ComboTipo.getSelectedItem().equals("Selecione")) {
                JOptionPane.showMessageDialog(this, "Selecione o tipo!");
                return;
            }

            if (ComboMarca.getSelectedItem().equals("Selecione")) {
                JOptionPane.showMessageDialog(this, "Selecione a marca!");
                return;
            }
            
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            boolean status;
            int resposta;

            p.setModelo(TxfModelo.getText());
            p.setCategoria(ComboCat.getSelectedItem().toString());
            p.setTipo(ComboTipo.getSelectedItem().toString());
            p.setMarca(ComboMarca.getSelectedItem().toString());
            p.setValor(Double.parseDouble(TxFValor.getText().trim().replace(",", ".")));
            p.setEstoque(Integer.parseInt(TxFEstoque.getText()));

            dao = new ProdutoDAO();
            status = dao.conectar();

            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar.");
            } else {

                if (modoEdicao) {
                    p.setId(idProdutoEdicao);
                    resposta = dao.atualizar(p);
                    JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
                } else {
                    resposta = dao.salvar(p);
                    JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
                }
            }
            TelaProdutos t = new TelaProdutos(usuarioLogado);
            t.setVisible(true);
            this.dispose();
            dao.desconectar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage());
        }

    }//GEN-LAST:event_BtnCadActionPerformed

    private void ComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoActionPerformed
        // TODO add your handling code here:
        ComboMarca.removeAllItems();

        String categoria = (String) ComboCat.getSelectedItem();

        if (categoria == null) {
            return;
        }

        switch (categoria) {
            case "Corda":
                ComboMarca.removeAllItems();
                ComboMarca.addItem("Selecione");
                ComboMarca.addItem("Cort");
                ComboMarca.addItem("Di Giorgio");
                ComboMarca.addItem("Eagle");
                ComboMarca.addItem("Epiphone");
                ComboMarca.addItem("Fender");
                ComboMarca.addItem("Giannini");
                ComboMarca.addItem("Gibson");
                ComboMarca.addItem("Hofma");
                ComboMarca.addItem("Ibanez");
                ComboMarca.addItem("Michael");
                ComboMarca.addItem("Rozini");
                ComboMarca.addItem("Seizi");
                ComboMarca.addItem("Strinberg");
                ComboMarca.addItem("SX");
                ComboMarca.addItem("Tagima");
                ComboMarca.addItem("Yamaha");
                ComboMarca.addItem("Outro");
                break;

            case "Sopro":
                ComboMarca.removeAllItems();
                ComboMarca.addItem("Selecione");
                ComboMarca.addItem("Buffet Crampon");
                ComboMarca.addItem("Eagle");
                ComboMarca.addItem("Hering");
                ComboMarca.addItem("Jupiter");
                ComboMarca.addItem("Michael");
                ComboMarca.addItem("Selmer");
                ComboMarca.addItem("Suzuki");
                ComboMarca.addItem("Weril");
                ComboMarca.addItem("Yamaha");
                ComboMarca.addItem("Outro");
                break;

            case "Percussão":
                ComboMarca.removeAllItems();
                ComboMarca.addItem("Selecione");
                ComboMarca.addItem("Alesis");
                ComboMarca.addItem("Aquarian");
                ComboMarca.addItem("Contemporânea");
                ComboMarca.addItem("Evans");
                ComboMarca.addItem("Gope");
                ComboMarca.addItem("Gretsch");
                ComboMarca.addItem("Izzo");
                ComboMarca.addItem("Ludwig");
                ComboMarca.addItem("Mapex");
                ComboMarca.addItem("Nagano");
                ComboMarca.addItem("Odery");
                ComboMarca.addItem("Pearl");
                ComboMarca.addItem("Remo");
                ComboMarca.addItem("RMV");
                ComboMarca.addItem("Tama");
                ComboMarca.addItem("Timbra");
                ComboMarca.addItem("Yamaha");
                ComboMarca.addItem("Outro");
                break;

            case "Teclas":
                ComboMarca.removeAllItems();
                ComboMarca.addItem("Selecione");
                ComboMarca.addItem("Casio");
                ComboMarca.addItem("Korg");
                ComboMarca.addItem("Kurzweil");
                ComboMarca.addItem("Medeli");
                ComboMarca.addItem("Nord");
                ComboMarca.addItem("Roland");
                ComboMarca.addItem("Yamaha");
                ComboMarca.addItem("Outro");
                break;

            case "Acessório":
                ComboMarca.removeAllItems();
                ComboMarca.addItem("Selecione");
                ComboMarca.addItem("Basso");
                ComboMarca.addItem("Behringer");
                ComboMarca.addItem("Boss");
                ComboMarca.addItem("D’Addario");
                ComboMarca.addItem("Dunlop");
                ComboMarca.addItem("Elixir");
                ComboMarca.addItem("Ernie Ball");
                ComboMarca.addItem("Focusrite");
                ComboMarca.addItem("Korg");
                ComboMarca.addItem("Landscape");
                ComboMarca.addItem("On-Stage");
                ComboMarca.addItem("Planet Waves");
                ComboMarca.addItem("Santo Angelo");
                ComboMarca.addItem("Shure");
                ComboMarca.addItem("Stay");
                ComboMarca.addItem("Vic Firth");
                ComboMarca.addItem("Zoom");
                ComboMarca.addItem("Outro");
                break;
        }


    }//GEN-LAST:event_ComboTipoActionPerformed

    private void ComboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCatActionPerformed
        // TODO add your handling code here:
        ComboTipo.removeAllItems();

        String categoria = (String) ComboCat.getSelectedItem();

        if (categoria == null) {
            return;
        }

        switch (categoria) {
            case "Corda":
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Violão");
                ComboTipo.addItem("Guitarra Elétrica");
                ComboTipo.addItem("Viola");
                ComboTipo.addItem("Baixo");
                ComboTipo.addItem("Contrabaixo");
                ComboTipo.addItem("Cavaquinho");
                ComboTipo.addItem("Bandolim");
                ComboTipo.addItem("Violino");
                ComboTipo.addItem("Violoncelo");
                ComboTipo.addItem("Outro");
                break;

            case "Sopro":
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Flauta");
                ComboTipo.addItem("Saxofone");
                ComboTipo.addItem("Clarinete");
                ComboTipo.addItem("Trompete");
                ComboTipo.addItem("Trombone");
                ComboTipo.addItem("Gaita");
                break;

            case "Percussão":
                ComboTipo.removeAllItems();
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Bateria");
                ComboTipo.addItem("Pandeiro");
                ComboTipo.addItem("Tamborim");
                ComboTipo.addItem("Triângulo");
                ComboTipo.addItem("Agogô");
                ComboTipo.addItem("Chocalho");
                ComboTipo.addItem("Outro");
                break;

            case "Teclas":
                ComboTipo.removeAllItems();
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Piano");
                ComboTipo.addItem("Teclado");
                ComboTipo.addItem("Sintetizador");
                ComboTipo.addItem("Acordeon");
                ComboTipo.addItem("Órgão");
                ComboTipo.addItem("Controladores MIDI");
                ComboTipo.addItem("Outro");
                break;

            case "Outro":
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Mesa de Som");
                ComboTipo.addItem("Berimbau");
                ComboTipo.addItem("Reco-reco");
                ComboTipo.addItem("Rabeca");
                ComboTipo.addItem("Produto de Limpeza");
                ComboTipo.addItem("Outro");
                break;

            case "Acessório":
                ComboTipo.removeAllItems();
                ComboTipo.addItem("Selecione");
                ComboTipo.addItem("Corda");
                ComboTipo.addItem("Palheta");
                ComboTipo.addItem("Correia");
                ComboTipo.addItem("Suporte");
                ComboTipo.addItem("Cabo");
                ComboTipo.addItem("Case");
                ComboTipo.addItem("Capotraste");
                ComboTipo.addItem("Outro");
                break;
        }
    }//GEN-LAST:event_ComboCatActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:
        TelaProdutos telaP = new TelaProdutos(usuarioLogado);
        telaP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void TxFEstoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxFEstoqueKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxFEstoqueKeyTyped

    private void TxFValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxFValorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            return;
        }

        if (c == ',' && !TxFValor.getText().contains(",")) {
            return;
        }

        evt.consume();
    }//GEN-LAST:event_TxFValorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCad;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JComboBox<String> ComboCat;
    private javax.swing.JComboBox<String> ComboMarca;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JTextField TxFEstoque;
    private javax.swing.JTextField TxFValor;
    private javax.swing.JTextField TxfModelo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
