package view;

import dao.ClienteDAO;
import dao.ProdutoDAO;
import dao.UsuarioDAO;
import dao.VendaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import java.time.LocalDate;
import java.text.DecimalFormat;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import model.Usuario;
import model.Venda;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chris
 */
public class TelaCadVenda extends javax.swing.JFrame {

    int idCliente;
    private final DecimalFormat df = new DecimalFormat("#,##0.00");
    double total;
    private List<Produto> produtosVenda;
    private String usuarioLogado;
    private TableRowSorter<DefaultTableModel> sorterProdutos;
    TableRowSorter<DefaultTableModel> sorterClientes;

    /**
     * Creates new form TelaCadVenda
     */
    public TelaCadVenda(String usuarioLogado) {
        this(usuarioLogado, new ArrayList<>());
    }

    public TelaCadVenda(String usuarioLogado, List<Produto> produtosVenda) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setLocationRelativeTo(null);
        ProdutoDAO daoP = new ProdutoDAO();
        daoP.listar(TableProdutos);
        ClienteDAO daoC = new ClienteDAO();
        daoC.listarIDNOME(TableCliente);
        this.usuarioLogado = usuarioLogado;
        this.produtosVenda = produtosVenda;

        TxfVendedor.setText(usuarioLogado);
        DefaultTableModel model = (DefaultTableModel) TblProdSel.getModel();
        DefaultTableModel modelProdutos = (DefaultTableModel) TableProdutos.getModel();
        sorterProdutos = new TableRowSorter<>(modelProdutos);
        TableProdutos.setRowSorter(sorterProdutos);
        model.setRowCount(0);

        DefaultTableModel modelCliente = (DefaultTableModel) TableCliente.getModel();
        sorterClientes = new TableRowSorter<>(modelCliente);
        TableCliente.setRowSorter(sorterClientes);

        ClienteDAO dao = new ClienteDAO();
        dao.listar(TableCliente);
    }

    TelaCadVenda() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxfCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnAdd1 = new javax.swing.JButton();
        TxfTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnAdd2 = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblProdSel = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProdutos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnAdd3 = new javax.swing.JButton();
        TxfVendedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxfBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Spinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Venda - SoundWave");

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxfCliente.setEditable(false);
        TxfCliente.setBackground(new java.awt.Color(255, 255, 255));
        TxfCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxfCliente.setForeground(new java.awt.Color(0, 0, 0));
        TxfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfClienteActionPerformed(evt);
            }
        });
        jPanel1.add(TxfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 180, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar por Tipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 20));

        BtnAdd1.setBackground(new java.awt.Color(25, 118, 210));
        BtnAdd1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd1.setText("Selecionar Cliente");
        BtnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 160, 40));

        TxfTotal.setEditable(false);
        TxfTotal.setBackground(new java.awt.Color(255, 255, 255));
        TxfTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxfTotal.setForeground(new java.awt.Color(0, 0, 0));
        TxfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfTotalActionPerformed(evt);
            }
        });
        jPanel1.add(TxfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 140, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 60, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        BtnAdd2.setBackground(new java.awt.Color(25, 118, 210));
        BtnAdd2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd2.setText("Adicionar Produto");
        BtnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 160, 40));

        BtnVoltar.setBackground(new java.awt.Color(25, 118, 210));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        TblProdSel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblProdSel);
        if (TblProdSel.getColumnModel().getColumnCount() > 0) {
            TblProdSel.getColumnModel().getColumn(1).setResizable(false);
            TblProdSel.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 780, 230));

        TableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Categoria", "Tipo", "Marca", "Valor", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1250, 290));

        jButton1.setBackground(new java.awt.Color(25, 118, 210));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remover Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 160, 40));

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableCliente);
        if (TableCliente.getColumnModel().getColumnCount() > 0) {
            TableCliente.getColumnModel().getColumn(0).setResizable(false);
            TableCliente.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 430, 230));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de Produtos Selecionado para Venda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lista de Produtos ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        BtnAdd3.setBackground(new java.awt.Color(25, 118, 210));
        BtnAdd3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAdd3.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd3.setText("Finalizar Venda");
        BtnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, 160, 40));

        TxfVendedor.setEditable(false);
        TxfVendedor.setBackground(new java.awt.Color(255, 255, 255));
        TxfVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxfVendedor.setForeground(new java.awt.Color(0, 0, 0));
        TxfVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfVendedorActionPerformed(evt);
            }
        });
        jPanel1.add(TxfVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 140, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vendedor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 100, 20));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("* Selecione um produto e clique em adicionar produto pra inclui-lo na venda.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        TxfBuscar.setBackground(new java.awt.Color(255, 255, 255));
        TxfBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxfBuscar.setForeground(new java.awt.Color(0, 0, 0));
        TxfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfBuscarActionPerformed(evt);
            }
        });
        TxfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxfBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(TxfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 22, 180, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cliente:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 70, 20));

        Spinner.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        Spinner.setBorder(null);
        jPanel1.add(Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 350, 100, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lista de Clientes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 402, 170, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:
        TelaVendas v = new TelaVendas(usuarioLogado);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void TxfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfTotalActionPerformed

    private void BtnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd1ActionPerformed
        // TODO add your handling code here:
        int linha = TableCliente.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
            return;
        }

        // Converte linha visível para linha do modelo
        int linhaModel = TableCliente.convertRowIndexToModel(linha);

        String cliente = TableCliente.getModel().getValueAt(linhaModel, 1).toString();
        TxfCliente.setText(cliente);
        idCliente = Integer.parseInt(TableCliente.getModel().getValueAt(linhaModel, 0).toString());


    }//GEN-LAST:event_BtnAdd1ActionPerformed

    private void BtnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd2ActionPerformed
        // TODO add your handling code here:
        try {
            int linha = TableProdutos.getSelectedRow();

            if (linha == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto pra adicionar!");
                Spinner.setValue(1);
                return;
            }

            int estoque = Integer.parseInt(TableProdutos.getValueAt(linha, 6).toString());
            int qtd = Integer.parseInt(Spinner.getValue().toString());

            if (estoque < qtd) {
                JOptionPane.showMessageDialog(null, "Estoque insuficiente!");
                Spinner.setValue(1);
                return;
            }

            int novoEstoque = estoque - qtd;
            DefaultTableModel modelProd = (DefaultTableModel) TableProdutos.getModel();
            modelProd.setValueAt(novoEstoque, linha, 6);

            int id = Integer.parseInt(TableProdutos.getValueAt(linha, 0).toString());
            String modelo = TableProdutos.getValueAt(linha, 1).toString();
            double valor = Double.parseDouble(TableProdutos.getValueAt(linha, 5).toString());

            DefaultTableModel modelSel = (DefaultTableModel) TblProdSel.getModel();

            boolean encontrado = false;

            for (int i = 0; i < modelSel.getRowCount(); i++) {

                int idTabela = Integer.parseInt(
                        modelSel.getValueAt(i, 0).toString()
                );

                if (idTabela == id) {
                    int qtdAtual = Integer.parseInt(
                            modelSel.getValueAt(i, 3).toString()
                    );

                    modelSel.setValueAt(qtdAtual + qtd, i, 3);
                    encontrado = true;
                    break;
                }
            }

            if (!encontrado) {
                modelSel.addRow(new Object[]{
                    id,
                    modelo,
                    valor,
                    qtd
                });
            }
            double totalAtual = 0;

            if (!TxfTotal.getText().trim().isEmpty()) {
                totalAtual = Double.parseDouble(
                        TxfTotal.getText().replace(",", ".")
                );
            }

            total = totalAtual + (valor * qtd);

            TxfTotal.setText(String.format("%.2f", total));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao adicionar produto: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnAdd2ActionPerformed

    private void TxfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxfClienteActionPerformed

    private void BtnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd3ActionPerformed
        // TODO add your handling code here:
        try {
            if (TxfCliente.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Verifique se um cliente está vinculado à venda!");
                return;
            }

            if (TblProdSel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "É preciso ter pelo menos um produto na venda!");
                return;
            }

            int opcao = JOptionPane.showConfirmDialog(
                    null,
                    "Tem certeza que deseja finalizar a venda?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (opcao != JOptionPane.YES_OPTION) {
                return;
            }

            UsuarioDAO daoUsuario = new UsuarioDAO();
            VendaDAO daoVenda = new VendaDAO();

            Venda v = new Venda();
            v.setData(new java.util.Date());
            v.setidVendedor(daoUsuario.pegarIdUsuario(usuarioLogado));
            v.setidCliente(idCliente);
            v.setValor(Double.parseDouble(TxfTotal.getText().replace(",", ".")));

            int status = daoVenda.salvar(v);
            if (status > 0) {
                JOptionPane.showMessageDialog(null, "Venda finalizada com sucesso!");

                ProdutoDAO daoP = new ProdutoDAO();

                for (int i = 0; i < TblProdSel.getRowCount(); i++) {
                    int idProduto = Integer.parseInt(TblProdSel.getValueAt(i, 0).toString());
                    int qtdVendida = Integer.parseInt(TblProdSel.getValueAt(i, 3).toString());

                    boolean atualizado = daoP.atualizarEstoque(idProduto, qtdVendida);
                    if (!atualizado) {
                        JOptionPane.showMessageDialog(null, "Erro ao atualizar estoque do produto ID: " + idProduto);
                    }
                }

                TxfCliente.setText("");
                TxfTotal.setText("0.00");
                Spinner.setValue(1);

                DefaultTableModel modelSel = (DefaultTableModel) TblProdSel.getModel();
                modelSel.setRowCount(0);

                idCliente = 0;
                total = 0;

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao finalizar a venda!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao finalizar venda: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnAdd3ActionPerformed

    private void TxfVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfVendedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelSel = (DefaultTableModel) TblProdSel.getModel();
        DefaultTableModel modelProd = (DefaultTableModel) TableProdutos.getModel();

        int linhaSel = TblProdSel.getSelectedRow();

        if (linhaSel == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para remover!");
            return;
        }

        int idProduto = Integer.parseInt(modelSel.getValueAt(linhaSel, 0).toString());
        double valor = Double.parseDouble(modelSel.getValueAt(linhaSel, 2).toString());
        int qtd = Integer.parseInt(modelSel.getValueAt(linhaSel, 3).toString());

        for (int i = 0; i < modelProd.getRowCount(); i++) {
            int idTabela = Integer.parseInt(modelProd.getValueAt(i, 0).toString());

            if (idTabela == idProduto) {
                int estoqueAtual = Integer.parseInt(modelProd.getValueAt(i, 6).toString());
                modelProd.setValueAt(estoqueAtual + qtd, i, 6);
                break;
            }
        }

        double totalAtual = 0;

        if (!TxfTotal.getText().trim().isEmpty()) {
            totalAtual = Double.parseDouble(
                    TxfTotal.getText().replace(",", ".")
            );
        }

        totalAtual -= (valor * qtd);

        if (totalAtual < 0) {
            totalAtual = 0;
        }

        TxfTotal.setText(String.format("%.2f", totalAtual));

        modelSel.removeRow(linhaSel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxfBuscarKeyReleased
        // TODO add your handling code here:
        String texto = TxfBuscar.getText().trim();

        if (texto.isEmpty()) {
            sorterProdutos.setRowFilter(null);
        } else {
            sorterProdutos.setRowFilter(
                    RowFilter.regexFilter("(?i)" + texto, 3)
            );
        }
    }//GEN-LAST:event_TxfBuscarKeyReleased

    private void TxfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfBuscarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String texto = jTextField1.getText().trim();

        if (texto.isEmpty()) {
            sorterClientes.setRowFilter(null);
        } else {
            sorterClientes.setRowFilter(
                    RowFilter.regexFilter("(?i)" + texto, 1)
            );
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadVenda("teste").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd1;
    private javax.swing.JButton BtnAdd2;
    private javax.swing.JButton BtnAdd3;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTable TableProdutos;
    private javax.swing.JTable TblProdSel;
    private javax.swing.JTextField TxfBuscar;
    private javax.swing.JTextField TxfCliente;
    private javax.swing.JTextField TxfTotal;
    private javax.swing.JTextField TxfVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
