package view;

import dao.ClienteDAO;
import dao.ProdutoDAO;
import view.TelaClientes;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Cliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chris
 */
public class TelaCadCliente extends javax.swing.JFrame {

    private boolean modoEdicao = false;
    private int linhaEdicao = -1;
    String usuarioLogado;
    private int idClienteEdicao = 0;

    /**
     * Creates new form TelaCadCliente
     */
    public TelaCadCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
    }

    TelaCadCliente(String usuarioLogado) {
        this();
        this.usuarioLogado = usuarioLogado;
    }

    public void ativarEdicao(
            int idCliente,
            String nome,
            String cpf,
            String telefone
    ) {
        modoEdicao = true;
        idClienteEdicao = idCliente;

        setTitle("Edição de Clientes - SoundWave");
        BtnCad.setText("Atualizar");
        title.setText("Editar Cliente");

        TxfNome.setText(nome);
        TxfCpf.setText(cpf);
        TxfTelefone.setText(telefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnVoltar = new javax.swing.JButton();
        BtnCad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxfCpf = new javax.swing.JFormattedTextField();
        TxfTelefone = new javax.swing.JFormattedTextField();
        TxfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro/Atualização de Cliente - SoundWave");

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVoltar.setBackground(new java.awt.Color(25, 118, 210));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        BtnCad.setBackground(new java.awt.Color(25, 118, 210));
        BtnCad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCad.setForeground(new java.awt.Color(255, 255, 255));
        BtnCad.setText("Salvar");
        BtnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 650, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        TxfCpf.setBackground(new java.awt.Color(255, 255, 255));
        TxfCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TxfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 650, 40));

        TxfTelefone.setBackground(new java.awt.Color(255, 255, 255));
        TxfTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TxfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxfTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxfTelefoneKeyTyped(evt);
            }
        });
        jPanel1.add(TxfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 650, 40));

        TxfNome.setBackground(new java.awt.Color(255, 255, 255));
        TxfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfNomeActionPerformed(evt);
            }
        });
        TxfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxfNomeKeyTyped(evt);
            }
        });
        jPanel1.add(TxfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 650, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Cadastro de Cliente");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfNomeActionPerformed

    private void BtnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadActionPerformed
        // TODO add your handling code here:

        try {
           
            if (TxfNome.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o nome!");
                TxfNome.requestFocus();
                return;
            }

            if (!TxfCpf.isEditValid()) {
                JOptionPane.showMessageDialog(this, "CPF inválido!");
                TxfCpf.requestFocus();
                return;
            }

            if (!TxfTelefone.isEditValid()) {
                JOptionPane.showMessageDialog(this, "Telefone inválido!");
                TxfTelefone.requestFocus();
                return;
            }

            String cpfLimpo = TxfCpf.getText().replaceAll("\\D", "");

            ClienteDAO dao = new ClienteDAO();

            if (!dao.conectar()) {
                JOptionPane.showMessageDialog(this, "Erro ao conectar.");
                return;
            }

      
            if (dao.cpfExiste(cpfLimpo, modoEdicao ? idClienteEdicao : 0)) {
                JOptionPane.showMessageDialog(this, "CPF já cadastrado!");
                TxfCpf.requestFocus();
                dao.desconectar();
                return;
            }

            Cliente c = new Cliente();
            c.setNome(TxfNome.getText());
            c.setCpf(cpfLimpo);
            c.setTelefone(TxfTelefone.getText().replaceAll("\\D", ""));

            int resposta;

            if (modoEdicao) {
                c.setId(idClienteEdicao);
                resposta = dao.atualizar(c);

                if (resposta == 1) {
                    JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar cliente.");
                }
            } else {
                resposta = dao.salvar(c);

                if (resposta == 1) {
                    JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar cliente.");
                }
            }

            dao.desconectar();

            TelaClientes t = new TelaClientes(usuarioLogado);
            t.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnCadActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:
        TelaClientes c = new TelaClientes(usuarioLogado);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void TxfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxfNomeKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || c == ' ') {
            return;
        }

        evt.consume();
    }//GEN-LAST:event_TxfNomeKeyTyped

    private void TxfTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxfTelefoneKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_TxfTelefoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCad;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JFormattedTextField TxfCpf;
    private javax.swing.JTextField TxfNome;
    private javax.swing.JFormattedTextField TxfTelefone;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
