package view;

import dao.ProdutoDAO;
import view.TelaCadProduto;
import view.TelaMenu;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chris
 */
public class TelaProdutos extends javax.swing.JFrame {

    TableRowSorter<DefaultTableModel> sorter;
    int modo = 0;
    String usuarioLogado;

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        ProdutoDAO dao = new ProdutoDAO();
        dao.listar(JTableProdutos);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        DefaultTableModel model = (DefaultTableModel) JTableProdutos.getModel();
        sorter = new TableRowSorter<>(model);
        JTableProdutos.setRowSorter(sorter);
    }

    TelaProdutos(String usuarioLogado) {
        this();
        this.usuarioLogado = usuarioLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnVoltar = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnCad = new javax.swing.JButton();
        BtnDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProdutos = new javax.swing.JTable();
        TxfBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos - SoundWave");

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVoltar.setBackground(new java.awt.Color(25, 118, 210));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        BtnEdit.setBackground(new java.awt.Color(25, 118, 210));
        BtnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEdit.setForeground(new java.awt.Color(255, 255, 255));
        BtnEdit.setText("Editar Produto");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 660, 170, 40));

        BtnCad.setBackground(new java.awt.Color(25, 118, 210));
        BtnCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCad.setForeground(new java.awt.Color(255, 255, 255));
        BtnCad.setText("Adicionar Produto");
        BtnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 170, 40));

        BtnDel.setBackground(new java.awt.Color(25, 118, 210));
        BtnDel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDel.setForeground(new java.awt.Color(255, 255, 255));
        BtnDel.setText("Excluir Produto");
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, 170, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por Tipo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, -1, -1));

        JTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Categoria", "Tipo", "Marca", "Valor", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableProdutos);
        if (JTableProdutos.getColumnModel().getColumnCount() > 0) {
            JTableProdutos.getColumnModel().getColumn(0).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(1).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(2).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(3).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(4).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(5).setResizable(false);
            JTableProdutos.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1440, 550));

        TxfBuscar.setBackground(new java.awt.Color(255, 255, 255));
        TxfBuscar.setForeground(new java.awt.Color(0, 0, 0));
        TxfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfBuscarActionPerformed(evt);
            }
        });
        TxfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxfBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(TxfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 50, 270, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produtos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadActionPerformed
        // TODO add your handling code here:

        TelaCadProduto cadP = new TelaCadProduto(usuarioLogado);
        cadP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCadActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:

        TelaMenu menu = new TelaMenu(usuarioLogado);
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        int linhaView = JTableProdutos.getSelectedRow();

        if (linhaView == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
            return;
        }

        int linhaModel = JTableProdutos.convertRowIndexToModel(linhaView);
        DefaultTableModel model = (DefaultTableModel) JTableProdutos.getModel();

        int id = Integer.parseInt(model.getValueAt(linhaModel, 0).toString());
        String modelo = model.getValueAt(linhaModel, 1).toString();
        String categoria = model.getValueAt(linhaModel, 2).toString();
        String tipo = model.getValueAt(linhaModel, 3).toString();
        String marca = model.getValueAt(linhaModel, 4).toString();
        String valor = model.getValueAt(linhaModel, 5).toString();
        String estoque = model.getValueAt(linhaModel, 6).toString();

        TelaCadProduto tela = new TelaCadProduto(usuarioLogado);
        tela.ativarEdicao(id, modelo, categoria, tipo, marca, valor, estoque);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        // TODO add your handling code here:
        int linha = JTableProdutos.getSelectedRow();
        int id = Integer.parseInt(JTableProdutos.getValueAt(linha, 0).toString());

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {
            ProdutoDAO dao = new ProdutoDAO();
            dao.excluir(id);
            dao.listar(JTableProdutos);
        } else {
            return;
        }
    }//GEN-LAST:event_BtnDelActionPerformed

    private void TxfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxfBuscarKeyReleased
        // TODO add your handling code here:
        String texto = TxfBuscar.getText();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(
                    RowFilter.regexFilter("(?i)" + texto, 3)
            );
        }


    }//GEN-LAST:event_TxfBuscarKeyReleased

    private void TxfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxfBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCad;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JTable JTableProdutos;
    private javax.swing.JTextField TxfBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
